apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
        - name: crudapi
          image: davisonfav/crud:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/training
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: crud
spec:
  selector:
    app: crud
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer